apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redis
spec:
  template:
    spec:
      volumes:
      - name: redis-persistent-storage
        # This must be set to null to address broken patch semantic.
        emptyDir: null
        gcePersistentDisk:
          pdName: redis-persistent-storage
